### ISSUE TITLE
Shorthands with unsupported attributes don’t apply

### ISSUE THREAD

**Issue by kinday** [maximkoretskiy/postcss-initial#12]
Easy way: don’t include attributes that are not supported widely into shorthands.
Hard way: build fallback according to specified list of browsers using `caniuse` as `autoprefixer` do.

Example of Chrome completely ignoring `font` shorthand:
![image](https://cloud.githubusercontent.com/assets/1751980/12218178/d094eb2e-b728-11e5-98c8-b905cf029e21.png)

**Comment by maximkoretskiy** [comment]
We can add more than one rule to handle this situation

Example

``` css
a {
  font: normal normal normal normal 100% normal normal; /* Browser applies this rule*/
  font: normal normal normal normal medium/normal normal normal;  /* Browser can`t parse this rule, so it uses previous */
}
```

@kinday What do You this about this solution?
