### ISSUE TITLE
Repeated processing causes duplicates

### ISSUE THREAD

**Issue by ChaosExAnima** [maximkoretskiy/postcss-initial#18]
Seeing an issue where the code causes duplicate properties if the fallback already exists.

Given this code:

``` css
selector {
    overflow: visible;
    overflow: initial;
    width: auto;
    width: initial;
}
```

Processing generates this:

``` css
selector {
    overflow: visible;
    overflow: visible;
    overflow: initial;
    width: auto;
    width: auto;
    width: initial;
}
```

This causes issues where the file is processed via a Grunt watch script or similar, as it can lead to hundreds of duplicate properties.
